homeassistant:
  enabled: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyUSB0
  adapter: ezsp
frontend:
  enabled: true
  port: 8080
advanced:
  log_level: info
version: 5
devices:
  '0xa4c13836a9308178':
    friendly_name: Rhythmus 1 этаж
